// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK_XOAhqptH_aCECwf9dxMpHwrWFIQk6c',
    appId: '1:623206073133:web:9ff57ceb31370201c009a4',
    messagingSenderId: '623206073133',
    projectId: 'waleed-shop',
    authDomain: 'waleed-shop.firebaseapp.com',
    storageBucket: 'waleed-shop.appspot.com',
    measurementId: 'G-R8KG2TJPCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeuCB4QHmKCtTkJ5_yBCYEq9u_LyjuP0M',
    appId: '1:623206073133:android:32b3eef38ed130d2c009a4',
    messagingSenderId: '623206073133',
    projectId: 'waleed-shop',
    storageBucket: 'waleed-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Dzct7NWFTI-mARGRxFt-6gTTg6BsPP8',
    appId: '1:623206073133:ios:8e6228aee1eb948bc009a4',
    messagingSenderId: '623206073133',
    projectId: 'waleed-shop',
    storageBucket: 'waleed-shop.appspot.com',
    iosClientId: '623206073133-ijra1ngcfhcegnnrd9pg64sjt3d0uevd.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppWaleed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Dzct7NWFTI-mARGRxFt-6gTTg6BsPP8',
    appId: '1:623206073133:ios:8e6228aee1eb948bc009a4',
    messagingSenderId: '623206073133',
    projectId: 'waleed-shop',
    storageBucket: 'waleed-shop.appspot.com',
    iosClientId: '623206073133-ijra1ngcfhcegnnrd9pg64sjt3d0uevd.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppWaleed',
  );
}
